name: CI

on: [push]

jobs:
  build-mvn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload jar
      uses: actions/upload-artifact@v1
      with:
        name: sandbox.jar
        path: target/sandbox.jar

  build-docker:

    needs: build-mvn
    runs-on: ubuntu-latest

    steps:
    - name: Download jar
      uses: actions/download-artifact@v1
      with:
        name: sandbox.jar
        path: docker/sandbox.jar